### ISSUE TITLE
NameError: name 'BiSeNetGhostEDA8v7' is not defined

### ISSUE THREAD

**Issue by zhang-pan** [nwpulab113/FastICENet#2]
Traceback (most recent call last):
  File "C:/Users/zhangpan/Desktop/FastICENet/train.py", line 427, in <module>
    train_model(args)
  File "C:/Users/zhangpan/Desktop/FastICENet/train.py", line 103, in train_model
    model = build_model(args.model, num_classes=args.classes)
  File "C:\Users\zhangpan\Desktop\FastICENet\builders\model_builder.py", line 6, in build_model
    return FastICENet(classes=num_classes)
  File "C:\Users\zhangpan\Desktop\FastICENet\model\FastICENet.py", line 264, in __init__
    super(BiSeNetGhostEDA8v7, self).__init__()
NameError: name 'BiSeNetGhostEDA8v7' is not defined

**Comment by nishishuini** [comment]
How did you solve it
